#NumPy

##NumPy'da dizi oluşturmak

In [1]:
import numpy as np

In [4]:
dizi = np.array([1,2,3,4,5])

In [5]:
type(dizi)

numpy.ndarray

In [8]:
#sıfırlardan oluşan dizi oluşturma
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#birlerden oluşan dizi oluşturma
np.ones((6,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
#belirlenen sayıdan oluşan bir dizi oluşturma
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
#belirli bir aralıkta bir dizi oluşturma
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
#random bir dizi oluşturma
np.random.normal(10,4,(2,3))

array([[ 6.93894539,  3.68278558,  9.17579853],
       [11.77494401,  4.87484539,  0.72072656]])

In [16]:
#random tamsayılardan oluşan bir dizi oluşturma
np.random.randint(0,10,(2,2))

array([[3, 2],
       [9, 2]])

##NumPy Dizilerinin Özellikleri

In [17]:
import numpy as np

In [19]:
dizi = np.random.randint(10,size=10)

In [20]:
#dizinin boyut sayısını alma
dizi.ndim

1

In [32]:
#dizinin şeklini alma
dizi.shape

(10,)

In [23]:
#dizinin büyüklüğünü alma
dizi.size

10

In [33]:
#dizinin tipini belirleme
dizi.dtype

dtype('int64')

In [25]:
dizi2 = np.random.randint(10,size=(2,3))

In [26]:
dizi2.ndim

2

In [29]:
dizi2.shape

(2, 3)

In [30]:
dizi2.size

6

In [31]:
dizi.dtype

dtype('int64')

In [35]:
#yeniden şekillendirme
dizi

array([9, 1, 0, 5, 3, 2, 7, 0, 0, 8])

In [39]:
a = dizi.reshape((5,2))
a

array([[9, 1],
       [0, 5],
       [3, 2],
       [7, 0],
       [0, 8]])

In [40]:
a.ndim

2

In [42]:
b = dizi.reshape(1,10)
b

array([[9, 1, 0, 5, 3, 2, 7, 0, 0, 8]])

In [43]:
#dizileri birleştirme
x = np.array([1,2,3])
y = np.array([4,5,6])

In [44]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [45]:
#iki boyutlu dizileri birleştirme
a = np.array([[1,2,3],[4,5,6]])

In [46]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
#dizileri ayırma
x = np.array([1,2,3,4,5,6])

In [52]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6])]

In [53]:
a,b,c = np.split(x,[3,5])

In [56]:
a

array([1, 2, 3])

In [57]:
b

array([4, 5])

In [58]:
c

array([6])

In [61]:
#iki boyutlu ayırma
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
k,l = np.vsplit(y, [2])

In [64]:
k

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
l

array([[6, 7, 8]])

In [67]:
k,l =np.hsplit(y,[2])

In [68]:
k

array([[0, 1],
       [3, 4],
       [6, 7]])

In [69]:
l

array([[2],
       [5],
       [8]])

In [77]:
#dizileri sıralama
array = np.array([4,5,6,3,1,2])

In [78]:
np.sort(array)

array([1, 2, 3, 4, 5, 6])

In [79]:
array

array([4, 5, 6, 3, 1, 2])

In [80]:
array.sort()

In [81]:
array

array([1, 2, 3, 4, 5, 6])

In [82]:
#iki boyutlu dizi sıralama
array2 = np.random.normal(5,20, (4,4))

In [83]:
array2

array([[  7.55275057,   1.02704977, -10.0007906 ,  15.69808119],
       [ 44.75485475,  17.90764298,  -5.60408348,   6.02738584],
       [  9.30629545,  33.47329898,  29.77050835,   6.97579975],
       [ -9.71337815,  -0.84342907,  53.78064652,  -9.48157325]])

In [85]:
np.sort(array2, axis=1)

array([[-10.0007906 ,   1.02704977,   7.55275057,  15.69808119],
       [ -5.60408348,   6.02738584,  17.90764298,  44.75485475],
       [  6.97579975,   9.30629545,  29.77050835,  33.47329898],
       [ -9.71337815,  -9.48157325,  -0.84342907,  53.78064652]])

In [87]:
np.sort(array2, axis=0)

array([[ -9.71337815,  -0.84342907, -10.0007906 ,  -9.48157325],
       [  7.55275057,   1.02704977,  -5.60408348,   6.02738584],
       [  9.30629545,  17.90764298,  29.77050835,   6.97579975],
       [ 44.75485475,  33.47329898,  53.78064652,  15.69808119]])

In [91]:
 #Dizi elemanlarına ulaşma
 a = np.random.randint(10, size=10)
 a

array([2, 8, 8, 6, 0, 7, 7, 3, 7, 2])

In [92]:
a[0]

2

In [93]:
a[-1]

2

In [95]:
b = np.random.randint(10, size=(2,3))

In [96]:
b

array([[0, 4, 3],
       [3, 1, 4]])

In [97]:
b[1][2]

4

In [98]:
b[1,2]

4

In [99]:
b[1,2] = 67

In [100]:
b

array([[ 0,  4,  3],
       [ 3,  1, 67]])

In [104]:
a

array([2, 8, 8, 6, 0, 7, 7, 3, 7, 2])

In [105]:
a[0:3]

array([2, 8, 8])

In [106]:
a[:3]

array([2, 8, 8])

In [107]:
a[3:]

array([6, 0, 7, 7, 3, 7, 2])

In [108]:
a[1::3]

array([8, 0, 3])

In [109]:
b

array([[ 0,  4,  3],
       [ 3,  1, 67]])

In [110]:
b[:,0]

array([0, 3])

In [111]:
b[:,2]

array([ 3, 67])

In [112]:
b[0,:]

array([0, 4, 3])

In [114]:
b[0:2, 0:2]

array([[0, 4],
       [3, 1]])

In [115]:
b[:,:2]

array([[0, 4],
       [3, 1]])

In [116]:
b[:,1:]

array([[ 4,  3],
       [ 1, 67]])

##Alt küme işlemleri

In [119]:
import numpy as np
a = np.random.randint(10,size=(4,4))
a

array([[4, 0, 2, 9],
       [9, 1, 9, 3],
       [0, 6, 4, 7],
       [6, 6, 4, 7]])

In [120]:
alt_a = a[0:2,0:2]
alt_a

array([[4, 0],
       [9, 1]])

In [123]:
alt_a[0,0] =555
alt_a[1,1] = 666

In [124]:
alt_a

array([[555,   0],
       [  9, 666]])

In [125]:
a

array([[555,   0,   2,   9],
       [  9, 666,   9,   3],
       [  0,   6,   4,   7],
       [  6,   6,   4,   7]])

##Matematiksel işlemler

In [129]:
a = np.random.randint(10, size=10)

In [130]:
a

array([1, 8, 9, 6, 6, 5, 8, 7, 8, 7])

In [135]:
a-2

array([-1,  6,  7,  4,  4,  3,  6,  5,  6,  5])

In [136]:
np.subtract(a,2)

array([-1,  6,  7,  4,  4,  3,  6,  5,  6,  5])

In [137]:
a+2

array([ 3, 10, 11,  8,  8,  7, 10,  9, 10,  9])

In [138]:
np.add(a,2)

array([ 3, 10, 11,  8,  8,  7, 10,  9, 10,  9])

In [139]:
a*2

array([ 2, 16, 18, 12, 12, 10, 16, 14, 16, 14])

In [140]:
np.multiply(a,2)

array([ 2, 16, 18, 12, 12, 10, 16, 14, 16, 14])

In [141]:
a/2

array([0.5, 4. , 4.5, 3. , 3. , 2.5, 4. , 3.5, 4. , 3.5])

In [142]:
np.divide(a,2)

array([0.5, 4. , 4.5, 3. , 3. , 2.5, 4. , 3.5, 4. , 3.5])

In [143]:
a**2

array([ 1, 64, 81, 36, 36, 25, 64, 49, 64, 49])

In [144]:
np.power(a,2)

array([ 1, 64, 81, 36, 36, 25, 64, 49, 64, 49])

In [145]:
a%2

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1])

In [146]:
np.mod(a,2)

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1])