#Pandas

##Pandasta seri oluşturmak 

In [ ]:
import pandas as pd

In [ ]:
a = pd.Series([5,6,4,7,9])

İlk kısımda index, ikinci kısımda değer yar alır

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
a.axes

[RangeIndex(start=0, stop=5, step=1)]

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.values

array([5, 6, 4, 7, 9])

In [ ]:
a.ndim

1

In [ ]:
a.head(2)

0    5
1    6
dtype: int64

In [ ]:
a.tail(2)

3    7
4    9
dtype: int64

In [ ]:
pd.Series([1,2,3,4,5],index = [5,4,3,2,1])

5    1
4    2
3    3
2    4
1    5
dtype: int64

In [ ]:
b = pd.Series([1,2,3,4,5],index = ["a","b","c","d","e"])

In [ ]:
b["a"]

1

In [ ]:
#serileri birleştirme
pd.concat([a,b])

0    5
1    6
2    4
3    7
4    9
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#numpy arrayi  pandas serisi yapma
import numpy as n
dizi = np.array([1,5,6,4])
seri = pd.Series(dizi)
seri

0    1
1    5
2    6
3    4
dtype: int64

##Eleman işlemleri

In [ ]:
seri[0]

1

In [ ]:
seri = pd.Series([3,4,5], index = ["a","b","c"])

In [ ]:
seri

a    3
b    4
c    5
dtype: int64

In [ ]:
seri.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
seri.keys

<bound method Series.keys of a    3
b    4
c    5
dtype: int64>

In [ ]:
list(seri.items())

[('a', 3), ('b', 4), ('c', 5)]

In [ ]:
seri.values

array([3, 4, 5])

In [ ]:
"a" in seri

True

In [ ]:
"d" in seri

False

In [ ]:
seri["a"] = 67

In [ ]:
seri

a    67
b     4
c     5
dtype: int64

In [ ]:
seri[["b","c"]]

b    4
c    5
dtype: int64

##Pandas DataFrame Oluşturma

In [ ]:
import pandas as pd

In [ ]:
l = [1,5,6,2,7]

In [ ]:
l

[1, 5, 6, 2, 7]

In [ ]:
pd.DataFrame(l, columns =["Veriler"])

Veriler
0        1
1        5
2        6
3        2
4        7

In [ ]:
dizi = np.arange(1,10).reshape((3,3))
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df =pd.DataFrame(dizi, columns = ["veri1","veri2","veri3"])
df

veri1  veri2  veri3
0      1      2      3
1      4      5      6
2      7      8      9

In [ ]:
df.columns = ("1","2","3")

In [ ]:
df

1  2  3
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
dizi1 = np.random.randint(10, size = 5)
dizi2 = np.random.randint(10, size = 5)
dizi3 = np.random.randint(10, size = 5)

In [ ]:
sozluk = {"veri1":dizi1, "veri2":dizi2 , "veri3":dizi3}

In [ ]:
df = pd.DataFrame(sozluk)
df

veri1  veri2  veri3
0      0      1      6
1      4      8      2
2      3      1      2
3      4      9      0
4      4      3      4

In [ ]:
 df["a"] = df["veri1"]/df["veri2"]
 df

veri1  veri2  veri3         a
0      0      1      6  0.000000
1      4      8      2  0.500000
2      3      1      2  3.000000
3      4      9      0  0.444444
4      4      3      4  1.333333

## Loc ve iLoc

In [1]:
import numpy as np
import pandas as pd

In [3]:
dizi = np.random.randint(1,30, size=(10,3))
dizi

array([[ 8, 24, 12],
       [23, 19, 19],
       [13, 11, 17],
       [12,  9, 26],
       [26, 16,  7],
       [ 9, 29,  8],
       [20, 26, 10],
       [13,  5, 22],
       [ 5, 14, 21],
       [12, 28, 14]])

In [4]:
df = pd.DataFrame(dizi, columns = ["veri1","veri2","veri3"])
df

veri1  veri2  veri3
0      8     24     12
1     23     19     19
2     13     11     17
3     12      9     26
4     26     16      7
5      9     29      8
6     20     26     10
7     13      5     22
8      5     14     21
9     12     28     14

In [5]:
#loc ; tanımlandığı şekli ile seçim yapmak için kullanılır
df.loc[0:3]

veri1  veri2  veri3
0      8     24     12
1     23     19     19
2     13     11     17
3     12      9     26

In [6]:
#iloc ; indeksleme mantığı ile seçim yapar
df.iloc[0:3]

veri1  veri2  veri3
0      8     24     12
1     23     19     19
2     13     11     17

loc girilen satırıda alır, iloc o satıra kadar olanları alır

##koşullu eleman işlemleri

In [7]:
df

veri1  veri2  veri3
0      8     24     12
1     23     19     19
2     13     11     17
3     12      9     26
4     26     16      7
5      9     29      8
6     20     26     10
7     13      5     22
8      5     14     21
9     12     28     14

In [9]:
df.veri1

0     8
1    23
2    13
3    12
4    26
5     9
6    20
7    13
8     5
9    12
Name: veri1, dtype: int64

In [10]:
df[df.veri1 > 20]

veri1  veri2  veri3
1     23     19     19
4     26     16      7

In [11]:
df[df.veri1 > 20]["veri1"]

1    23
4    26
Name: veri1, dtype: int64

In [15]:
df[((df.veri1) > 20) & (df.veri3 < 10)] 

veri1  veri2  veri3
4     26     16      7

In [17]:
pd.concat([df[:3],df[:4]])

veri1  veri2  veri3
0      8     24     12
1     23     19     19
2     13     11     17
0      8     24     12
1     23     19     19
2     13     11     17
3     12      9     26

In [19]:
?pd.concat

In [20]:
pd.concat([df[:3],df[:4]], ignore_index = True)

veri1  veri2  veri3
0      8     24     12
1     23     19     19
2     13     11     17
3      8     24     12
4     23     19     19
5     13     11     17
6     12      9     26

In [21]:
df.columns

Index(['veri1', 'veri2', 'veri3'], dtype='object')

In [22]:
df1 = pd.DataFrame({'calisanlar': ['Ali','burak','huseyin'],'grup':['muhasebe','muhendis','developer']})

In [23]:
df1

calisanlar       grup
0        Ali   muhasebe
1      burak   muhendis
2    huseyin  developer

In [24]:
df2 = pd.DataFrame({'calisanlar': ['Ali','burak','huseyin'],'yas':['35 ','20','45']})

In [25]:
df2

calisanlar  yas
0        Ali  35 
1      burak   20
2    huseyin   45

In [26]:
pd.merge(df1,df2)

calisanlar       grup  yas
0        Ali   muhasebe  35 
1      burak   muhendis   20
2    huseyin  developer   45

In [27]:
pd.merge(df1,df2, on = "calisanlar")

calisanlar       grup  yas
0        Ali   muhasebe  35 
1      burak   muhendis   20
2    huseyin  developer   45

## Toplulaştırma ve Gruplama

In [28]:
import seaborn as sns

In [29]:
df = sns.load_dataset("planets")

In [30]:
 df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [31]:
df.shape

(1035, 6)

In [33]:
#değerlerin ortalamasını alır
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [35]:
df["number"].mean()

1.7855072463768116

In [36]:
df.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [37]:
df.min()

method            Astrometry
number                     1
orbital_period     0.0907063
mass                  0.0036
distance                1.35
year                    1989
dtype: object

In [38]:
df.max()

method            Transit Timing Variations
number                                    7
orbital_period                       730000
mass                                     25
distance                               8500
year                                   2014
dtype: object

In [39]:
df.std()

number                1.240976
orbital_period    26014.728304
mass                  3.818617
distance            733.116493
year                  3.972567
dtype: float64

In [42]:
df["number"].var()

1.5400218652762578

In [43]:
#veri setini tanımlar
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [44]:
df.describe().T

count         mean  ...       75%       max
number          1035.0     1.785507  ...     2.000       7.0
orbital_period   992.0  2002.917596  ...   526.005  730000.0
mass             513.0     2.638161  ...     3.040      25.0
distance         808.0   264.069282  ...   178.500    8500.0
year            1035.0  2009.070531  ...  2012.000    2014.0

[5 rows x 8 columns]

In [45]:
df.tail()

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [46]:
#veri setindeki eksik değerleri atarak tanımlar
df.dropna().describe().T

count         mean          std  ...       50%        75%      max
number          498.0     1.734940     1.175720  ...     1.000     2.0000      6.0
orbital_period  498.0   835.778671  1469.128259  ...   357.000   999.6000  17337.5
mass            498.0     2.509320     3.636274  ...     1.245     2.8675     25.0
distance        498.0    52.068213    46.596041  ...    39.940    59.3325    354.0
year            498.0  2007.377510     4.167284  ...  2009.000  2011.0000   2014.0

[5 rows x 8 columns]

##Pivot Tablolar


In [47]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [49]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [52]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [53]:
titanic.pivot_table("survived",index = "sex", columns= "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [54]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [57]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [58]:
titanic.pivot_table("survived", ["sex", age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

##Veri okuma

In [61]:
#csv dosyası okuma
pd.read_csv("/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [63]:
#metin dosyası okuma
pd.read_csv("/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [64]:
#excel dosyası okuma
pd.read_excel("/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [70]:
df = pd.read_excel("/ornekx.xlsx")
df

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [71]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df.columns = ["a","b","c"]

In [73]:
df

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0